### ISSUE TITLE
[BUG] "Connect anyway" problem on mobile 

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-RPGF4#172] opened 2024-06-29 06:55 UTC
**Describe the bug**
When I try to connect my wallet on my phone, by tapping on “connect anyway” ( my address has no badge) 
I got an error in all of my tries 

**To Reproduce**
1. Go to mobile app
2. Click on "connect"
3. copy the link
4. open the link in browser
5. connect a address without badge
6. tap on "connect anyway"

**Screenshots**

https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/6429467f-c395-42e9-9e69-034387539a19

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - Browser safari/chrome

**Comment by mmahdigh** [comment] 2024-06-30 11:56
I can't reproduce this one. If you could give us any errors that you see in the network tab and/or the console tab, we could investigate them further.

**Comment by MoeNick** [comment] 2024-06-30 11:58
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/80677512/692205d0-14ef-4b55-b4c1-851ffb41f695)
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/80677512/4b684717-b0cd-46b8-8824-92045762c97e)

@mmahdigh

**Comment by maryjaf** [comment] 2024-06-30 12:13
> I can't reproduce this one. If you could give us any errors that you see in the network tab and/or the console tab, we could investigate them further.

I see that "my user has already connected" but I also see "Connect" button 

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/a46d3e8f-3795-4b06-9281-ba00973e5d5d)

**Comment by mmahdigh** [comment] 2024-06-30 12:34
> > I can't reproduce this one. If you could give us any errors that you see in the network tab and/or the console tab, we could investigate them further.
> 
> I see that "my user has already connected" but I also see "Connect" button
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/344464150-a46d3e8f-3795-4b06-9281-ba00973e5d5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NDk4OTYsIm5iZiI6MTcxOTc0OTU5NiwicGF0aCI6Ii8xMTE1MjkxODUvMzQ0NDY0MTUwLWE0NmQzZThmLTM3OTUtNGIwNi05MjgxLWJhMDA5NzNlNWQ1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxMjEzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzQyYThkMjk2NGEzNDRmMzQ5MzhmM2ZhNzJmY2JlM2YyOTBhNmRlNjc0NzIyMmMwMmMwMWEyMWIyYmVjZTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t3T2kPVGzGjmyBSrpIps6NJMGTqrSC25U6dSCzMyNbs)

Due to a bug that's going to be fixed by #177, users' connect data could end up in a scenario in which the connect flow is incomplete leading to corrupt data in the DB. I found only one such instance in our staging db and I guess that was you. Give this another shot and if it's not fixed, just let me know.

**Comment by maryjaf** [comment] 2024-06-30 13:20
I’ve checked on staging and try to connect Mary.jafarimehr@gmail.com to an account without badge on my mobile and I got error 

https://staging.app.pairwise.vote/connect?otp=535075


![IMG_2891](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/b9820ae5-9177-4cab-8d8b-2c7fd65b182c)
![IMG_2892](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/c4f0834d-7f68-432f-861e-b0e4613c10a2)

**Comment by mmahdigh** [comment] 2024-06-30 14:36
> I’ve checked on staging and try to connect [Mary.jafarimehr@gmail.com](mailto:Mary.jafarimehr@gmail.com) to an account without badge on my mobile and I got error
> 
> https://staging.app.pairwise.vote/connect?otp=535075
> 
> ![IMG_2891](https://private-user-images.githubusercontent.com/111529185/344468082-b9820ae5-9177-4cab-8d8b-2c7fd65b182c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTgxODksIm5iZiI6MTcxOTc1Nzg4OSwicGF0aCI6Ii8xMTE1MjkxODUvMzQ0NDY4MDgyLWI5ODIwYWU1LTkxNzctNGNhYi04ZDhiLTJjN2ZkNjViMTgyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxNDMxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjliZDFkZmRjMmU1ZGVjYWRlMTAyOGY1N2U4Nzg3MTVhNWQ2NjY1NTdmMjg1NjJhZTBhODFiNjdhZDM3ZmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xirSSyqONNUMYg4Sh7HdkNdyjnwLbv3yGIUQEZPyzRM) ![IMG_2892](https://private-user-images.githubusercontent.com/111529185/344468087-c4f0834d-7f68-432f-861e-b0e4613c10a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTgxODksIm5iZiI6MTcxOTc1Nzg4OSwicGF0aCI6Ii8xMTE1MjkxODUvMzQ0NDY4MDg3LWM0ZjA4MzRkLTdmNjgtNDMyZi04NjFlLWIwZTQ2MTNjMTBhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxNDMxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzc2MWIwZDdiZjQ0NWNhODA4NmEyNTYwYTJmMjdlYzQ0ZGVmNWVhZjY0MjA3YTY5YWJmYzRlOGQwM2I4YmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-MG2HoC_Y1flE-DIBc3GJiB0pnrqfjKkDocE4QffCgg)

That error shows up when your OTP has either expired or is outright wrong. Maybe your OTP has expired in the time you go from mobile to desktop? It's unlikely because they have a 4-hour lifespan.

I couldn't see any OTP record for "535075". If you could replicate this error, let me know your smart wallet address. We can also do the steps together so I can watch the DB live to see what's exactly happening. I couldn't reproduce this for myself.

**Comment by mmahdigh** [comment] 2024-06-30 14:46
Okay, I wasn't aware that we had changed the `Please try again` error message to this "There's no Pairwise account...". It could be any random error happening and it's not necessarily related to the OTP validity. Again, if you send me the exact error you get in your browser network tab, it'd be much more helpful.

**Comment by maryjaf** [comment] 2024-07-01 05:44
> Okay, I wasn't aware that we had changed the `Please try again` error message to this `There's no Pairwise account...`. It could be any random error happening and it's not necessarily related to the OTP validity. Again, if you send me the exact error you get in your browser network tab, it'd be much more helpful.

"There is no ..." is shown in this page /connect?otp  and "try again" is shown in   /categories.

but I haven't received this error today with my account 
Since this error happened for others, it would be good that be checked by other device and accounts, could you please test it @MoeNick

**Comment by MoeNick** [comment] 2024-07-01 05:51
I assigned the new flow of removing OTP to @alireza-sharifpour and he said we only have one error here so I give him this message In the desktop flow second screen. 
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/80677512/2d7612b4-f59d-4eab-8b07-c469c8352361)

I still cant get what's the problem with that? if we can connect with no badges, so we shouldn't show this error message and let the user go to next step. right? @mmahdigh @maryjaf

**Comment by mmahdigh** [comment] 2024-07-01 08:33
> I assigned the new flow of removing OTP to @alireza-sharifpour and he said we only have one error here so I give him this message In the desktop flow second screen. ![image](https://private-user-images.githubusercontent.com/80677512/344558099-2d7612b4-f59d-4eab-8b07-c469c8352361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjI4MDQsIm5iZiI6MTcxOTgyMjUwNCwicGF0aCI6Ii84MDY3NzUxMi8zNDQ1NTgwOTktMmQ3NjEyYjQtZjU5ZC00ZWFiLThiMDctYzQ2OWM4MzUyMzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4MjgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYTA3ZTA2NzRiNjIyY2RhNTQ2MDEzYmU0Mjg0YjdiMjVkNmNkODJhYzIyMGY3YWU3NTk3YzJlNzY1MTljZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O6gPg_cgDL-grfzjexIyi__Pb8SPfW3szkSqQdC0GEU)
> 
> I still cant get what's the problem with that? if we can connect with no badges, so we shouldn't show this error message and let the user go to next step. right? @mmahdigh @maryjaf

The problem is that a lot of things can to wrong in this screen and the message is only describing one of them. The OP address could be already connected, the OTP could be invalid, the OTP could be expired, bandada identity creation, the user's internet connection, etc.

For all of the above we're showing that message whereas previously we generically just showed "Please try again later".

**Comment by MoeNick** [comment] 2024-07-01 08:37
Ok if we have different error statuses / code  I can give the copy. Or if you can put the error messages here, I  an put  the translation. Is it good?

**Comment by mmahdigh** [comment] 2024-07-01 09:23
> Ok if we have different error statuses / code I can give the copy. Or if you can put the error messages here, I an put the translation. Is it good?

Seems fair. But let's track it in a new issue as it needs changes in both the backend & frontend.

Also, let's try to see if the current issue can be replicated or not.

**Closed** 2024-07-15 12:51 UTC
Labels: bug
